apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bu53xpcgw-nodejs 
  janus-idp.io/tekton: bu53xpcgw-nodejs
  backstage.io/kubernetes-id: bu53xpcgw-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bu53xpcgw-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml