apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bu53xpcgw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bu53xpcgw-nodejs 
  name: bu53xpcgw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bu53xpcgw-nodejs 
